# Generated by Django 5.2.17 on 2026-10-01 02:37

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('categoria', models.CharField(choices=[('alergias-alimentares', 'Alergias alimentares'), ('nutricao-clinica', 'Nutrição clínica'), ('microbiota', 'Microbiota e saúde intestinal'), ('obesidade-glp1', 'Obesidade e GLP-1'), ('massa-muscular', 'Massa muscular e sarcopenia'), ('longevidade', 'Nutrição na longevidade'), ('oncologica', 'Nutrição oncológica'), ('bariatrica', 'Bariátrica'), ('ingredientes', 'Ciência dos ingredientes')], max_length=30)),
                ('resumo', models.CharField(blank=True, max_length=300)),
                ('corpo', models.TextField()),
                ('publicado', models.BooleanField(default=True)),
                ('publicado_em', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ['-publicado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'cupons',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FaixaFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2, unique=True, verbose_name='estado (UF)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor do frete (R$)')),
                ('prazo_dias', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='prazo (dias úteis)')),
            ],
            options={
                'verbose_name': 'frete por estado',
                'verbose_name_plural': 'frete por estado',
                'ordering': ['uf'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comprar', 'Quero comprar produtos Mase'), ('profissional', 'Sou profissional de saúde'), ('cdmo', 'Quero desenvolver minha marca — CDMO'), ('ingredientes', 'Quero comprar ingredientes'), ('distribuidor', 'Quero representar/distribuir a Mase'), ('hospital', 'Sou hospital/clínica'), ('outros', 'Outros assuntos')], max_length=15)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_contato', 'Em contato'), ('proposta', 'Proposta enviada'), ('convertido', 'Convertido'), ('perdido', 'Perdido')], default='novo', max_length=12)),
                ('nome', models.CharField(max_length=120)),
                ('empresa', models.CharField(blank=True, max_length=120)),
                ('cnpj', models.CharField(blank=True, max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('mensagem', models.TextField(blank=True)),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='dados do formulário')),
                ('responsavel', models.CharField(blank=True, max_length=80, verbose_name='consultor responsável')),
                ('notas', models.TextField(blank=True, verbose_name='anotações internas')),
                ('consentimento', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=60)),
                ('foco', models.CharField(blank=True, max_length=160, verbose_name='resumo curto')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição da página')),
                ('status', models.CharField(choices=[('desenvolvimento', 'Em desenvolvimento'), ('lancada', 'Lançada')], default='desenvolvimento', max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('literatura', 'Literatura científica'), ('ficha', 'Ficha técnica'), ('info', 'Informação nutricional'), ('paciente', 'Material para pacientes'), ('webinar', 'Webinar'), ('evento', 'Evento'), ('aula', 'Aula'), ('protocolo', 'Protocolo educacional')], max_length=12)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo', models.FileField(blank=True, upload_to='materiais/')),
                ('link', models.URLField(blank=True, verbose_name='link (webinar, evento, aula)')),
                ('publicado', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'materiais',
                'ordering': ['tipo', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PontoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('loja', 'Loja especializada'), ('farmacia', 'Farmácia'), ('clinica', 'Clínica'), ('distribuidor', 'Distribuidor autorizado')], max_length=15)),
                ('cidade', models.CharField(max_length=80)),
                ('uf', models.CharField(max_length=2)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('site', models.URLField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ponto de venda',
                'verbose_name_plural': 'pontos de venda',
                'ordering': ['uf', 'cidade', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='RotaContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comprar', 'Quero comprar produtos Mase'), ('profissional', 'Sou profissional de saúde'), ('cdmo', 'Quero desenvolver minha marca — CDMO'), ('ingredientes', 'Quero comprar ingredientes'), ('distribuidor', 'Quero representar/distribuir a Mase'), ('hospital', 'Sou hospital/clínica'), ('outros', 'Outros assuntos')], max_length=15, unique=True)),
                ('responsavel', models.CharField(blank=True, max_length=80, verbose_name='responsável')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail do responsável')),
            ],
            options={
                'verbose_name': 'rota de contato',
                'verbose_name_plural': 'rotas de contato',
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencia_dias', models.PositiveSmallIntegerField(choices=[(30, 'A cada 30 dias'), (60, 'A cada 60 dias'), (90, 'A cada 90 dias')], default=30)),
                ('proxima_entrega', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Aguardando 1º pagamento'), ('ativa', 'Ativa'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada')], default='pendente', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to=settings.AUTH_USER_MODEL)),
                ('cupom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='loja.cupom')),
            ],
            options={
                'verbose_name': 'assinatura Mase Contínua',
                'verbose_name_plural': 'assinaturas Mase Contínua',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nutricionista', 'Nutricionista clínico'), ('alergista', 'Alergista / Imunologista'), ('nutrologo', 'Nutrólogo'), ('gastroenterologista', 'Gastroenterologista'), ('pediatra', 'Pediatra'), ('alergopediatra', 'Alergopediatra'), ('endocrinologista', 'Endocrinologista'), ('bariatrico', 'Bariátrico (cirurgia / equipe)'), ('oncologista', 'Oncologista'), ('geriatra', 'Geriatra'), ('medico', 'Médico(a) de outra especialidade'), ('outro', 'Outro profissional da nutrição clínica')], max_length=20, verbose_name='profissão / especialidade')),
                ('conselho', models.CharField(blank=True, choices=[('CRM', 'CRM — Conselho Regional de Medicina'), ('CRN', 'CRN — Conselho Regional de Nutrição'), ('OUTRO', 'Outro conselho')], max_length=5)),
                ('registro_profissional', models.CharField(blank=True, max_length=40, verbose_name='número do registro')),
                ('registro_uf', models.CharField(blank=True, max_length=2, verbose_name='UF do registro')),
                ('cnpj', models.CharField(blank=True, max_length=14, verbose_name='CNPJ do hospital/clínica')),
                ('instituicao', models.CharField(blank=True, max_length=120, verbose_name='hospital / clínica')),
                ('telefone', models.CharField(max_length=20)),
                ('instagram', models.CharField(blank=True, max_length=60)),
                ('chave_pix', models.CharField(blank=True, max_length=77, verbose_name='chave Pix para receber')),
                ('sobre', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Em análise'), ('aprovado', 'Aprovado'), ('recusado', 'Não aprovado')], default='pendente', max_length=10)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Desconto que o cliente ganha ao usar o cupom deste profissional.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='desconto para o paciente (%)')),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 = sem comissão. Calculada sobre o valor dos produtos com desconto (sem frete). Confirme antes as regras do conselho profissional.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='comissão (%)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parceiro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profissional de saúde',
                'verbose_name_plural': 'profissionais de saúde',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='cupom',
            name='parceiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupons', to='loja.parceiro'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando pagamento'), ('pago', 'Pago'), ('enviado', 'Enviado'), ('cancelado', 'Cancelado'), ('expirado', 'Pix expirado')], default='aguardando', max_length=12)),
                ('forma_pagamento', models.CharField(choices=[('pix', 'Pix'), ('cartao', 'Cartão de crédito ou débito')], default='pix', max_length=10)),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=8)),
                ('rua', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=80)),
                ('bairro', models.CharField(max_length=80)),
                ('cidade', models.CharField(max_length=80)),
                ('uf', models.CharField(max_length=2)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cupom_codigo', models.CharField(blank=True, max_length=20)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desconto_continua', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('comissao_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frete', models.DecimalField(decimal_places=2, max_digits=8)),
                ('frete_nome', models.CharField(blank=True, max_length=60)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mp_payment_id', models.CharField(blank=True, max_length=40)),
                ('pix_copia_cola', models.TextField(blank=True)),
                ('pix_qr_base64', models.TextField(blank=True)),
                ('pix_expira_em', models.DateTimeField(blank=True, null=True)),
                ('parcelas', models.PositiveSmallIntegerField(default=1)),
                ('cartao_final', models.CharField(blank=True, max_length=4, verbose_name='4 últimos dígitos do cartão')),
                ('cartao_bandeira', models.CharField(blank=True, max_length=30, verbose_name='bandeira do cartão')),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('codigo_rastreio', models.CharField(blank=True, max_length=40)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('assinatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='loja.assinatura')),
                ('cupom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='loja.cupom')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'A pagar'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='pendente', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paga_em', models.DateTimeField(blank=True, null=True)),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comissoes', to='loja.parceiro')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comissao', to='loja.pedido')),
            ],
            options={
                'verbose_name': 'comissão',
                'verbose_name_plural': 'comissões',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='assinatura',
            name='origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='loja.pedido'),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('sabor', models.CharField(blank=True, max_length=80, verbose_name='sabor / apresentação curta')),
                ('tipo', models.CharField(choices=[('produto', 'Produto'), ('kit', 'Kit')], default='produto', max_length=10)),
                ('categoria', models.CharField(blank=True, choices=[('whey', 'Whey Protein'), ('creatina', 'Creatina'), ('colageno', 'Colágeno & Vitaminas'), ('outros', 'Barras & Aminoácidos')], max_length=20)),
                ('objetivo', models.CharField(blank=True, help_text='Use somente objetivos permitidos pela regulamentação aplicável.', max_length=120, verbose_name='objetivo nutricional')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('selos', models.CharField(blank=True, help_text='Separe por vírgula. Ex: Sem lactose, Sem glúten', max_length=200)),
                ('composicao', models.TextField(blank=True, verbose_name='composição')),
                ('apresentacao', models.TextField(blank=True, verbose_name='apresentação')),
                ('modo_uso', models.TextField(blank=True, verbose_name='modo de uso')),
                ('informacao_nutricional', models.TextField(blank=True, verbose_name='informação nutricional')),
                ('ingredientes', models.TextField(blank=True)),
                ('alergenicos', models.TextField(blank=True, verbose_name='alergênicos')),
                ('diferenciais', models.TextField(blank=True)),
                ('perguntas', models.TextField(blank=True, help_text='Uma pergunta por bloco: 1ª linha = pergunta, linhas seguintes = resposta. Separe blocos com uma linha em branco.', verbose_name='perguntas frequentes')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='preço (R$)')),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('permite_assinatura', models.BooleanField(default=True, verbose_name='participa do Mase Contínua')),
                ('peso_kg', models.DecimalField(decimal_places=3, default=0.5, max_digits=6, verbose_name='peso (kg)')),
                ('largura_cm', models.PositiveIntegerField(default=12, verbose_name='largura (cm)')),
                ('altura_cm', models.PositiveIntegerField(default=18, verbose_name='altura (cm)')),
                ('comprimento_cm', models.PositiveIntegerField(default=12, verbose_name='comprimento (cm)')),
                ('cor1', models.CharField(default='#0D2356', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Use o formato #RRGGBB.')], verbose_name='cor 1 da embalagem')),
                ('cor2', models.CharField(default='#1B4A9C', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Use o formato #RRGGBB.')], verbose_name='cor 2 da embalagem')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('linha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='loja.linha')),
            ],
            options={
                'ordering': ['ordem', 'nome', 'sabor'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=220)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='loja.pedido')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='loja.assinatura')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produto')),
            ],
        ),
    ]
